export const metadata = {
  title: "About page",
  description: "About page of the application generated by Nextjs"
}

const About = () => {
  return (
    <div>About Page</div>
  )
}

export default About;